cssvars.bt:
  label: Theme CSS Variables
  type: mapping
  mapping:
    # Body
    body_bg:
      type: cssvars_color
      label: Body Background Color
    body_bg_light:
      type: cssvars_color
      label: Body Background Light Color
    body_bg_dark:
      type: cssvars_color
      label: Body Background Dark Color
    body_color:
      type: cssvars_color
      label: Body Text Color
    # Block
    block_bg_color:
      type: cssvars_color
      label: Block Background Color
    block_text_color:
      type: cssvars_color
      label: Block Text Color
    # Content
    caption_text_color:
      type: cssvars_color
      label: Caption Text Color
    intro_text_color:
      type: cssvars_color
      label: Intro Text Color
    # Titles
    page_title_color:
      type: cssvars_color
      label: Page Title Color
    section_title_color:
      type: cssvars_color
      label: Section Title Color
    block_title_color:
      type: cssvars_color
      label: Block Title Color
    article_title_color:
      type: cssvars_color
      label: Article Title Color
    blog_title_color:
      type: cssvars_color
      label: Blog Title Color
    # Link
    link_color:
      type: cssvars_color
      label: Link Color
    link_hover_color:
      type: cssvars_color
      label: Link Hover Color
    button_link_color:
      type: cssvars_color
      label: Button Link Color
    # Theme Colors
    success:
      type: cssvars_color
      label: Success
    info:
      type: cssvars_color
      label: Info
    warning:
      type: cssvars_color
      label: Warning
    danger:
      type: cssvars_color
      label: Danger
    light:
      type: cssvars_color
      label: Light
    dark:
      type: cssvars_color
      label: Dark
    blue:
      type: cssvars_color
      label: Blue
    indigo:
      type: cssvars_color
      label: Indigo
    purple:
      type: cssvars_color
      label: Purple
    pink:
      type: cssvars_color
      label: Pink
    red:
      type: cssvars_color
      label: Red
    orange:
      type: cssvars_color
      label: Orange
    yellow:
      type: cssvars_color
      label: Yellow
    green:
      type: cssvars_color
      label: Green
    teal:
      type: cssvars_color
      label: Teal
    cyan:
      type: cssvars_color
      label: Cyan
    primary:
      type: cssvars_color
      label: Color Primary
    primary_050:
      type: cssvars_color
      label: Color Primary 50
    primary_100:
      type: cssvars_color
      label: Color Primary 100
    primary_200:
      type: cssvars_color
      label: Color Primary 200
    primary_300:
      type: cssvars_color
      label: Color Primary 300
    primary_400:
      type: cssvars_color
      label: Color Primary 400
    primary_500:
      type: cssvars_color
      label: Color Primary 500
    primary_600:
      type: cssvars_color
      label: Color Primary 600
    primary_700:
      type: cssvars_color
      label: Color Primary 700
    primary_800:
      type: cssvars_color
      label: Color Primary 800
    primary_900:
      type: cssvars_color
      label: Color Primary 900
    secondary:
      type: cssvars_color
      label: Color Secondary
    secondary_050:
      type: cssvars_color
      label: Color Secondary 50
    secondary_100:
      type: cssvars_color
      label: Color Secondary 100
    secondary_200:
      type: cssvars_color
      label: Color Secondary 200
    secondary_300:
      type: cssvars_color
      label: Color Secondary 300
    secondary_400:
      type: cssvars_color
      label: Color Secondary 400
    secondary_500:
      type: cssvars_color
      label: Color Secondary 500
    secondary_600:
      type: cssvars_color
      label: Color Secondary 600
    secondary_700:
      type: cssvars_color
      label: Color Secondary 700
    secondary_800:
      type: cssvars_color
      label: Color Secondary 800
    secondary_900:
      type: cssvars_color
      label: Color Primary 900
    accent:
      type: cssvars_color
      label: Color Accent
    accent_050:
      type: cssvars_color
      label: Color Accent 50
    accent_100:
      type: cssvars_color
      label: Color Accent 100
    accent_200:
      type: cssvars_color
      label: Color Accent 200
    accent_300:
      type: cssvars_color
      label: Color Accent 300
    accent_400:
      type: cssvars_color
      label: Color Accent 400
    accent_500:
      type: cssvars_color
      label: Color Accent 500
    accent_600:
      type: cssvars_color
      label: Color Accent 600
    accent_700:
      type: cssvars_color
      label: Color Accent 700
    accent_800:
      type: cssvars_color
      label: Color Accent 800
    accent_900:
      type: cssvars_color
      label: Color Accent 900
    gray_100:
      type: cssvars_color
      label: Color Gray 100
    gray_200:
      type: cssvars_color
      label: Color Gray 200
    gray_300:
      type: cssvars_color
      label: Color Gray 300
    gray_400:
      type: cssvars_color
      label: Color Gray 400
    gray_500:
      type: cssvars_color
      label: Color Gray 500
    gray_600:
      type: cssvars_color
      label: Color Gray 600
    gray_700:
      type: cssvars_color
      label: Color Gray 700
    gray_800:
      type: cssvars_color
      label: Color Gray 800
    gray_900:
      type: cssvars_color
      label: Color Gray 900
    # Theme Colors RGB
    success_rgb:
      type: cssvars_color
      label: Success RGB
    info_rgb:
      type: cssvars_color
      label: Info RGB
    warning_rgb:
      type: cssvars_color
      label: Warning RGB
    danger_rgb:
      type: cssvars_color
      label: Danger RGB
    light_rgb:
      type: cssvars_color
      label: Light RGB
    dark_rgb:
      type: cssvars_color
      label: Dark RGB
    blue_rgb:
      type: cssvars_color
      label: Blue RGB
    indigo_rgb:
      type: cssvars_color
      label: Indigo RGB
    purple_rgb:
      type: cssvars_color
      label: Purple RGB
    pink_rgb:
      type: cssvars_color
      label: Pink RGB
    red_rgb:
      type: cssvars_color
      label: Red RGB
    orange_rgb:
      type: cssvars_color
      label: Orange RGB
    yellow_rgb:
      type: cssvars_color
      label: Yellow RGB
    green_rgb:
      type: cssvars_color
      label: Green RGB
    teal_rgb:
      type: cssvars_color
      label: Teal RGB
    cyan_rgb:
      type: cssvars_color
      label: Cyan RGB
    primary_rgb:
      type: cssvars_color
      label: Color Primario RGB
    primary_050_rgb:
      type: cssvars_color
      label: Color Primario 50 RGB
    primary_100_rgb:
      type: cssvars_color
      label: Color Primario 100 RGB
    primary_200_rgb:
      type: cssvars_color
      label: Color Primario 200 RGB
    primary_300_rgb:
      type: cssvars_color
      label: Color Primario 300 RGB
    primary_400_rgb:
      type: cssvars_color
      label: Color Primario 400 RGB
    primary_500_rgb:
      type: cssvars_color
      label: Color Primario 500 RGB
    primary_600_rgb:
      type: cssvars_color
      label: Color Primario 600 RGB
    primary_700_rgb:
      type: cssvars_color
      label: Color Primario 700 RGB
    primary_800_rgb:
      type: cssvars_color
      label: Color Primario 800 RGB
    primary_900_rgb:
      type: cssvars_color
      label: Color Primario 900 RGB
    secondary_rgb:
      type: cssvars_color
      label: Color Secundario RGB
    secondary_050_rgb:
      type: cssvars_color
      label: Color Secundario 50 RGB
    secondary_100_rgb:
      type: cssvars_color
      label: Color Secundario 100 RGB
    secondary_200_rgb:
      type: cssvars_color
      label: Color Secundario 200 RGB
    secondary_300_rgb:
      type: cssvars_color
      label: Color Secundario 300 RGB
    secondary_400_rgb:
      type: cssvars_color
      label: Color Secundario 400 RGB
    secondary_500_rgb:
      type: cssvars_color
      label: Color Secundario 500 RGB
    secondary_600_rgb:
      type: cssvars_color
      label: Color Secundario 600 RGB
    secondary_700_rgb:
      type: cssvars_color
      label: Color Secundario 700 RGB
    secondary_800_rgb:
      type: cssvars_color
      label: Color Secundario 800 RGB
    secondary_900_rgb:
      type: cssvars_color
      label: Color Secundario 900 RGB
    accent_rgb:
      type: cssvars_color
      label: Color Acento RGB
    accent_050_rgb:
      type: cssvars_color
      label: Color Acento 50 RGB
    accent_100_rgb:
      type: cssvars_color
      label: Color Acento 100 RGB
    accent_200_rgb:
      type: cssvars_color
      label: Color Acento 200 RGB
    accent_300_rgb:
      type: cssvars_color
      label: Color Acento 300 RGB
    accent_400_rgb:
      type: cssvars_color
      label: Color Acento 400 RGB
    accent_500_rgb:
      type: cssvars_color
      label: Color Acento 500 RGB
    accent_600_rgb:
      type: cssvars_color
      label: Color Acento 600 RGB
    accent_700_rgb:
      type: cssvars_color
      label: Color Acento 700 RGB
    accent_800_rgb:
      type: cssvars_color
      label: Color Acento 800 RGB
    accent_900_rgb:
      type: cssvars_color
      label: Color Acento 900 RGB
    gray_100_rgb:
      type: cssvars_color
      label: Color Gris 100 RGB
    gray_200_rgb:
      type: cssvars_color
      label: Color Gris 200 RGB
    gray_300_rgb:
      type: cssvars_color
      label: Color Gris 300 RGB
    gray_400_rgb:
      type: cssvars_color
      label: Color Gris 400 RGB
    gray_500_rgb:
      type: cssvars_color
      label: Color Gris 500 RGB
    gray_600_rgb:
      type: cssvars_color
      label: Color Gris 600 RGB
    gray_700_rgb:
      type: cssvars_color
      label: Color Gris 700 RGB
    gray_800_rgb:
      type: cssvars_color
      label: Color Gris 800 RGB
    gray_900_rgb:
      type: cssvars_color
      label: Color Gris 900 RGB
