cssvars.bt:
  label: Theme CSS Variables
  type: mapping
  mapping:
    # Body
    body_bg:
      type: cssvars_color
      label: Body Background Color
    body_bg_light:
      type: cssvars_color
      label: Body Background Light Color
    body_bg_dark:
      type: cssvars_color
      label: Body Background Dark Color
    body_color:
      type: cssvars_color
      label: Body Text Color
    # Block
    block_bg_color:
      type: cssvars_color
      label: Block Background Color
    block_text_color:
      type: cssvars_color
      label: Block Text Color
    # Content
    caption_text_color:
      type: cssvars_color
      label: Caption Text Color
    intro_text_color:
      type: cssvars_color
      label: Intro Text Color
    # Title
    section_title_color:
      type: cssvars_color
      label: Section Title Color
    block_title_color:
      type: cssvars_color
      label: Block Title Color
    article_title_color:
      type: cssvars_color
      label: Article Title Color
    blog_title_color:
      type: cssvars_color
      label: Blog Title Color
    # Link
    link_color:
      type: cssvars_color
      label: Link Color
    link_hover_color:
      type: cssvars_color
      label: Link Hover Color
    # Theme Colors
    blue:
      type: cssvars_color
      label: Blue
    indigo:
      type: cssvars_color
      label: Indigo
    purple:
      type: cssvars_color
      label: Purple
    pink:
      type: cssvars_color
      label: Pink
    red:
      type: cssvars_color
      label: Red
    orange:
      type: cssvars_color
      label: Orange
    yellow:
      type: cssvars_color
      label: Yellow
    green:
      type: cssvars_color
      label: Green
    teal:
      type: cssvars_color
      label: Teal
    cyan:
      type: cssvars_color
      label: Cyan
    primary:
      type: cssvars_color
      label: Color Primary
    primary_050:
      type: cssvars_color
      label: Color Primary 50
    primary_100:
      type: cssvars_color
      label: Color Primary 100
    primary_200:
      type: cssvars_color
      label: Color Primary 200
    primary_300:
      type: cssvars_color
      label: Color Primary 300
    primary_400:
      type: cssvars_color
      label: Color Primary 400
    primary_500:
      type: cssvars_color
      label: Color Primary 500
    primary_600:
      type: cssvars_color
      label: Color Primary 600
    primary_700:
      type: cssvars_color
      label: Color Primary 700
    primary_800:
      type: cssvars_color
      label: Color Primary 800
    primary_900:
      type: cssvars_color
      label: Color Primary 900
    secondary:
      type: cssvars_color
      label: Color Secondary
    secondary_050:
      type: cssvars_color
      label: Color Secondary 50
    secondary_100:
      type: cssvars_color
      label: Color Secondary 100
    secondary_200:
      type: cssvars_color
      label: Color Secondary 200
    secondary_300:
      type: cssvars_color
      label: Color Secondary 300
    secondary_400:
      type: cssvars_color
      label: Color Secondary 400
    secondary_500:
      type: cssvars_color
      label: Color Secondary 500
    secondary_600:
      type: cssvars_color
      label: Color Secondary 600
    secondary_700:
      type: cssvars_color
      label: Color Secondary 700
    secondary_800:
      type: cssvars_color
      label: Color Secondary 800
    secondary_900:
      type: cssvars_color
      label: Color Primary 900
    accent:
      type: cssvars_color
      label: Color Accent
    accent_050:
      type: cssvars_color
      label: Color Accent 50
    accent_100:
      type: cssvars_color
      label: Color Accent 100
    accent_200:
      type: cssvars_color
      label: Color Accent 200
    accent_300:
      type: cssvars_color
      label: Color Accent 300
    accent_400:
      type: cssvars_color
      label: Color Accent 400
    accent_500:
      type: cssvars_color
      label: Color Accent 500
    accent_600:
      type: cssvars_color
      label: Color Accent 600
    accent_700:
      type: cssvars_color
      label: Color Accent 700
    accent_800:
      type: cssvars_color
      label: Color Accent 800
    accent_900:
      type: cssvars_color
      label: Color Accent 900
    gray_100:
      type: cssvars_color
      label: Color Gray 100
    gray_200:
      type: cssvars_color
      label: Color Gray 200
    gray_300:
      type: cssvars_color
      label: Color Gray 300
    gray_400:
      type: cssvars_color
      label: Color Gray 400
    gray_500:
      type: cssvars_color
      label: Color Gray 500
    gray_600:
      type: cssvars_color
      label: Color Gray 600
    gray_700:
      type: cssvars_color
      label: Color Gray 700
    gray_800:
      type: cssvars_color
      label: Color Gray 800
    gray_900:
      type: cssvars_color
      label: Color Gray 900
