<?php

/**
 * @file
 * Provides a theme colors entity type.
 */

use Drupal\Core\Config\FileStorage;
use Drupal\Core\Render\Element;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function bt_theme_colors_theme() {
  return [
    'theme_colors' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for theme colors templates.
 *
 * Default template: theme-colors.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the theme colors
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_theme_colors(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function bt_theme_colors_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish theme colorss.
      $storage = \Drupal::entityTypeManager()->getStorage('theme_colors');
      $theme_colors_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($theme_colors_ids) as $theme_colors) {
        $theme_colors->set('status', FALSE);
        $theme_colors->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize theme colorss.
      $storage = \Drupal::entityTypeManager()->getStorage('theme_colors');
      $theme_colors_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($theme_colors_ids) as $theme_colors) {
        $theme_colors->setOwnerId(0);
        $theme_colors->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function bt_theme_colors_user_predelete(UserInterface $account) {
  // Delete theme colorss.
  $storage = \Drupal::entityTypeManager()->getStorage('theme_colors');
  $theme_colors_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $theme_colorss = $storage->loadMultiple($theme_colors_ids);
  $storage->delete($theme_colorss);
  // Delete old revisions.
  $theme_colors_ids = $storage->getQuery()
    ->allRevisions()
    ->condition('uid', $account->id())
    ->execute();
  foreach (array_keys($theme_colors_ids) as $revision_id) {
    $storage->deleteRevision($revision_id);
  }
}

/**
 * Update theme_colors's fields.
 */
function bt_theme_colors_update_9101() {
  $entity_type = 'theme_colors';

  // Delete unused fields (removed the prefix field_bt_).
  $fields_to_remove = [
    'article_title_color', 
    'block_bg_color',
    'block_text_color',
    'block_title_color',
    'blog_title_color',
    'body_bg',
    'body_bg_dark',
    'body_bg_light',
    'body_color',
    'button_link_color',
    'caption_text_color',
    'intro_text_color',
    'link_color',
    'link_hover_color',
    'page_title_color',
    'section_title_color'
  ];

  $bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo($entity_type);
  foreach ($bundles as $bundle) {
    foreach ($fields_to_remove as $field_id) {
      if ($field_instance = FieldConfig::loadByName($entity_type, $bundle, 'field_bt_' . $field_id)) {
        $field_instance->delete();
      }

      if ($field_storage = FieldStorageConfig::loadByName($entity_type, 'field_bt_' . $field_id)) {
        $field_storage->delete();
      }
    }
  }

  // Add new color fields.
  $config_factory = \Drupal::service('config.factory');
  $config_storage = \Drupal::service('config.storage');
  $config_path = \Drupal::service('extension.list.module')->getPath('bt_theme_colors') . '/config/install';
  $source = new FileStorage($config_path); 

  foreach (['primary', 'secondary', 'accent', 'gray'] as $color) {
    foreach (['050', '100', '200', '300', '400', '500', '600', '700', '800', '900'] as $shade) {
      $storage_config_file = 'field.storage.theme_colors.field_bt_' . $color . '_' . $shade;  
      $field_config_file = 'field.field.theme_colors.theme_colors.field_bt_' . $color . '_' . $shade;
      
      // Add storage.
      $config_storage->write($storage_config_file, $source->read($storage_config_file));

      // Add field.
      $config_storage->write($field_config_file, $source->read($field_config_file));
    }
  }

  // Update form display.
  $form_display_config = 'core.entity_form_display.theme_colors.theme_colors.default';
  $config_factory->getEditable($form_display_config)->delete();
  $config_storage->write($form_display_config, $source->read($form_display_config));
  
  // Update view display.
  $view_display_config = 'core.entity_view_display.theme_colors.theme_colors.default';
  $config_factory->getEditable($view_display_config)->delete();
  $config_storage->write($view_display_config, $source->read($view_display_config));

  // Update cssvars config.
  $cssvars_config = 'cssvars.bt';
  $config_factory->getEditable($cssvars_config)->delete();
  $config_storage->write($cssvars_config, $source->read($cssvars_config));
}
